tare_planner_node:
  ros__parameters:
    sub_start_exploration_topic_ : /start_exploration
    sub_terrain_map_topic_ : /terrain_map
    sub_terrain_map_ext_topic_ : /terrain_map_ext
    sub_state_estimation_topic_ : /state_estimation_at_scan
    sub_registered_scan_topic_ : /registered_scan
    sub_coverage_boundary_topic_ : /sensor_coverage_planner/coverage_boundary
    sub_viewpoint_boundary_topic_ : /navigation_boundary
    sub_nogo_boundary_topic_ : /sensor_coverage_planner/nogo_boundary
    sub_joystick_topic_ : /joy
    sub_reset_waypoint_topic_ : /reset_waypoint
    pub_exploration_finish_topic_ : exploration_finish
    pub_runtime_breakdown_topic_ : runtime_breakdown
    pub_runtime_topic_ : /runtime
    pub_waypoint_topic_ : /way_point
    pub_momentum_activation_count_topic_ : momentum_activation_count        # use_momentum，在遇到岔路时，起到岔路选择后的方向保持作用

    kAutoStart : true
    kRushHome : true
    kUseTerrainHeight : false
    kCheckTerrainCollision : true
    kExtendWayPoint : true
    kUseLineOfSightLookAheadPoint : true
    kNoExplorationReturnHome : true
    kExtendWayPointDistanceBig : 8.0          # waypoint最远距离，默认值4.0
    kExtendWayPointDistanceSmall : 3.5        # waypoint最近距离，默认值1.5
    kKeyposeCloudDwzFilterLeafSize : 0.2
    kRushHomeDist : 5.0
    kAtHomeDistThreshold : 0.5
    kTerrainCollisionThreshold : 0.5
    kLookAheadDistance : 8.0
    kUseMomentum : false 
    kDirectionChangeCounterThr : 6
    kDirectionNoChangeCounterThr : 5
    kResetWaypointJoystickAxesID : 2

    # PlanningEnv
    kUseFrontier : true
    kFrontierClusterTolerance : 1.0
    kFrontierClusterMinSize : 10                        # 前沿簇的最小值，在狭小空间，减小该值有助于发现前沿
    kUseCoverageBoundaryOnFrontier : false              # 是否只考虑探索边界以内的frontier
    kUseCoverageBoundaryOnObjectSurface : false         # 是否只考虑探索边界以内的物体表面

    # Rolling occupancy grid
    rolling_occupancy_grid/resolution_x : 0.3
    rolling_occupancy_grid/resolution_y : 0.3
    rolling_occupancy_grid/resolution_z : 0.3

    kSurfaceCloudDwzLeafSize : 0.3              # 探索不完整时，缩小这个参数有助于解决问题
    kCollisionCloudDwzLeafSize : 0.2
    kKeyposeCloudStackNum : 5
    kPointCloudRowNum : 50
    kPointCloudColNum : 50
    kPointCloudLevelNum : 30
    kMaxCellPointNum : 100000
    kPointCloudCellSize : 18.0
    kPointCloudCellHeight : 1.8
    kPointCloudManagerNeighborCellNum : 5
    kCoverCloudZSqueezeRatio : 2.0

    # KeyposeGraph
    keypose_graph/kAddNodeMinDist : 1.0
    keypose_graph/kAddNonKeyposeNodeMinDist : 0.5
    keypose_graph/kAddEdgeConnectDistThr : 3.0
    keypose_graph/kAddEdgeToLastKeyposeDistThr : 3.0
    keypose_graph/kAddEdgeVerticalThreshold : 1.0
    keypose_graph/kAddEdgeCollisionCheckResolution : 0.4
    keypose_graph/kAddEdgeCollisionCheckRadius : 0.4
    keypose_graph/kAddEdgeCollisionCheckPointNumThr : 1

    # ViewPointManager
    viewpoint_manager/number_x : 50             # x轴视点数量，默认值40，缩小有助于提升探索效果
    viewpoint_manager/number_y : 50             # y轴视点数量，默认值40，缩小有助于提升探索效果
    viewpoint_manager/number_z : 1
    viewpoint_manager/resolution_x : 0.6        # x轴视点分辨率,每个视点间距离，缩小有助于提升探索效果
    viewpoint_manager/resolution_y : 0.6
    viewpoint_manager/resolution_z : 0.0
    kConnectivityHeightDiffThr : 0.25
    kGreedyViewPointSampleRange : 3
    kLocalPathOptimizationItrMax : 10
    kViewPointCollisionMargin : 0.5             # viewpoint碰撞检测范围，如果这个范围内有障碍物，说明当前viewpoint有碰撞风险，不可选
    kViewPointCollisionMarginZPlus : 0.5
    kViewPointCollisionMarginZMinus : 0.5
    kCollisionGridZScale : 1.0
    kCollisionGridResolutionX : 0.2
    kCollisionGridResolutionY : 0.2
    kCollisionGridResolutionZ : 0.0
    kCollisionPointThr : 1
    kLineOfSightStopAtNearestObstacle : false
    kViewPointHeightFromTerrain : 0.75
    kViewPointHeightFromTerrainChangeThreshold : 0.6        # 判断为障碍物的地形高度阈值
    kCheckDynamicObstacleCollision : false
    kCollisionFrameCountMax : 3

    kSensorRange : 7.5                          # 传感器最大探测范围，默认3.0
    kNeighborRange : 3.0                        # 相邻视点之间距离阈值，默认1.5
    kCoverageOcclusionThr : 0.3
    kCoverageDilationRadius : 0.5

    # Grid World
    kGridWorldXNum : 121
    kGridWorldYNum : 121
    kGridWorldZNum : 121
    kGridWorldCellHeight : 3.0                  # local planning horizon的高
    kGridWorldNearbyGridNum : 5
    kMinAddPointNumSmall : 40                   # 减小该参数有利于提升探索效果
    kMinAddPointNumBig : 60
    kMinAddFrontierPointNum : 20                # 减小该参数有利于提升探索效果
    kCellExploringToCoveredThr : 1
    kCellCoveredToExploringThr: 10
    kCellExploringToAlmostCoveredThr: 10
    kCellAlmostCoveredToExploringThr: 20
    kCellUnknownToExploringThr: 1

    # Visualization
    kExploringSubspaceMarkerColorGradientAlpha : true
    kExploringSubspaceMarkerColorMaxAlpha : 0.8
    kExploringSubspaceMarkerColorR : 0.0
    kExploringSubspaceMarkerColorG : 1.0
    kExploringSubspaceMarkerColorB : 0.0
    kExploringSubspaceMarkerColorA : 1.0
    kLocalPlanningHorizonMarkerColorR : 0.0
    kLocalPlanningHorizonMarkerColorG : 1.0
    kLocalPlanningHorizonMarkerColorB : 0.0
    kLocalPlanningHorizonMarkerColorA : 1.0
    kLocalPlanningHorizonMarkerWidth : 0.3
    kLocalPlanningHorizonHeight : 3.0